# https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html

icons_format = "{icon}"

[theme]
[theme.overrides]
idle_bg = "#111111"
idle_fg = "#888888"  # gray
info_bg = "#111111"
info_fg = "#93a1a1"
good_bg = "#111111"
good_fg = "#859900"  # olive
warning_bg  = "#111111"
warning_fg  = "#b58900"  # orange
critical_bg = "#111111"
critical_fg = "#bc1e1e"  # red
separator = "|"
separator_bg = "#111111"
separator_fg = "#888888"  # gray

[[block]]
block = "maildir"
format = " $icon $status.eng(w:1) "
inboxes = [
    "~/Maildir/FJFI/*",
]
interval = 10
threshold_critical = 1

[[block]]
block = "net"
device = "wlan0"
format = " $icon ($signal_strength at $ssid, $bitrate) {$ip|} "
inactive_format = ""
missing_format = ""
[block.theme_overrides]
idle_fg = "#1793d0"  # blue

[[block]]
block = "net"
device = "eth0"
format = " $icon {$ip|down} "
[block.theme_overrides]
idle_fg = "#1793d0"  # blue

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $max "
chip = "*-isa-*"
good = 20
idle = 55
info = 70
warning = 80

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) "

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "sound"
show_volume_when_muted = false
format = " $icon{ $volume.eng(w:2)|} "
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a, %d %b %Y %H:%M:%S')"
[block.theme_overrides]
idle_fg = "#dddddd"  # white
