# browser is the shell (/bin/sh) command executed once the proxy starts.
# When browser exits, the proxy exits. An extra env var PROXY is available.
#
# Here, we use a separate Chrome instance in Incognito mode, so that
# it can run (and be waited for) alongside the default one, and that
# it maintains no state across runs. To configure this browser open a
# normal window in it, settings will be preserved.
browser = """
    chromium \
    --user-data-dir="/tmp/captive-browser-$USER" \
    --proxy-server="socks5://$PROXY" \
    --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost" \
    --no-first-run --no-default-browser-check \
    --new-window --incognito \
    http://example.org
"""

# dhcp-dns is the shell (/bin/sh) command executed to obtain the DHCP
# DNS server address. The first match of an IPv4 regex is used.
# IPv4 only, because let's be real, it's a captive portal.
#
# To install the systemd-networkd-dns command, run:
#
#  $ go get github.com/FiloSottile/captive-browser/cmd/systemd-networkd-dns
#
#dhcp-dns = "$(go env GOPATH)/bin/systemd-networkd-dns wlan0"
#dhcp-dns = "ip route | grep default | awk '{ print $3 }'"
# this command selects the *first* DNS server in the networkctl output
#dhcp-dns = "networkctl status | grep DNS | awk '{print $2}'"
# this command selects the *last* DNS server in the networkctl output
dhcp-dns = "networkctl status --json=short | jq -r '.Interfaces | map(select(.DNS) | .DNS) | .[] | map(.Address) | map(join(\".\")) | .[]' | tail -n1"

# socks5-addr is the listen address for the SOCKS5 proxy server.
socks5-addr = "localhost:1666"

# bind-device is the interface over which outbound connections (both HTTP
# and DNS) will be established. It can be used to avoid address space collisions
# but it requires CAP_NET_RAW or root privileges. Disabled by default.
#bind-device = "wlan0"
